In [ ]:
import pandas as pd  
import numpy as np  
import tensorflow as tf  
from sklearn.metrics import explained_variance_score,mean_absolute_error,median_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction import DictVectorizer

In [ ]:
from google.colab import files
!gdown --id '16yyF4iTT9XoZ8LoMMxqI6G0oNqYB1EvN' --output dataset
!ls

Downloading...
From: https://drive.google.com/uc?id=16yyF4iTT9XoZ8LoMMxqI6G0oNqYB1EvN
To: /content/dataset
100% 966k/966k [00:00<00:00, 61.1MB/s]
data  dataset  datasets  hour.csv  sample_data


In [ ]:
import pandas as pd
import numpy as np
data = pd.read_csv('datasets')
data.head()

instant  season  yr  mnth  hr  ...   hum  windspeed  casual  registered  cnt
0        5       1   0     1   4  ...  0.75     0.0000       0           1    1
1        6       1   0     1   5  ...  0.75     0.0896       0           1    1
2       31       1   0     1   7  ...  0.76     0.1940       0           1    1
3       50       1   0     1   4  ...  0.47     0.3881       0           1    1
4       72       1   0     1   2  ...  0.63     0.1343       0           1    1

[5 rows x 16 columns]

In [ ]:
X=data.drop('cnt',axis=1)
y=data['cnt']

In [ ]:
vec_y=DictVectorizer(sparse=False)

In [ ]:
target = data[['cnt']]

In [ ]:
y = vec_y.fit_transform(target.to_dict(orient='record'))

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:1490: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  FutureWarning,


In [ ]:
print(y)

[[  1.]
 [  1.]
 [  1.]
 ...
 [968.]
 [970.]
 [976.]]


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
y_train_onehot = np_utils.to_categorical(y_train)  #one_hot轉換
y_test_onehot = np_utils.to_categorical(y_test)
X_train_normalize=X_train/255  #標準
X_test_normalize=X_test/255

In [ ]:
print(y_test_onehot)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
from keras.utils import np_utils

In [ ]:
from keras.models import Sequential
from keras.layers import Dense,Activation
from keras.optimizers import SGD

In [ ]:
model = Sequential()

In [ ]:
model.add(Dense(500,input_dim=15))
model.add(Activation('sigmoid'))

In [ ]:
model.add(Dense(500))
model.add(Activation('sigmoid'))

In [ ]:
model.add(Dense(971))
model.add(Activation('softmax'))


In [ ]:
model.compile(loss='mse',optimizer=SGD(learning_rate=0.2),metrics=['accuracy'])

In [ ]:
model.fit(X_train_normalize,y_train_onehot, batch_size=300,epochs=20)

Epoch 1/20
47/47 [==============================] - 2s 36ms/step - loss: 0.0010 - accuracy: 0.0018
Epoch 2/20
47/47 [==============================] - 2s 36ms/step - loss: 0.0010 - accuracy: 0.0018
Epoch 3/20
47/47 [==============================] - 2s 36ms/step - loss: 0.0010 - accuracy: 0.0018
Epoch 4/20
47/47 [==============================] - 2s 36ms/step - loss: 0.0010 - accuracy: 0.0018
Epoch 5/20
47/47 [==============================] - 2s 35ms/step - loss: 0.0010 - accuracy: 0.0018
Epoch 6/20
47/47 [==============================] - 2s 36ms/step - loss: 0.0010 - accuracy: 0.0018
Epoch 7/20
47/47 [==============================] - 2s 36ms/step - loss: 0.0010 - accuracy: 0.0018
Epoch 8/20
47/47 [==============================] - 2s 35ms/step - loss: 0.0010 - accuracy: 0.0018
Epoch 9/20
47/47 [==============================] - 2s 36ms/step - loss: 0.0010 - accuracy: 0.0018
Epoch 10/20
47/47 [==============================] - 2s 36ms/step - loss: 0.0010 - accuracy: 0.0018
Epoch 11/

In [ ]:
y_predict = model.predict(X_test_normalize)

In [121]:
from sklearn import metrics

metrics.mean_squared_error(y_test_onehot,y_predict)
print('RMSE：', np.sqrt(metrics.mean_squared_error(y_test_onehot,y_predict)))

ValueError: ignored

In [122]:
def mape(y_test_onehot, y_predict):
    return np.mean(np.abs((y_predict - y_test_onehot) / (y_test_onehot +1))) * 100
print('MAPE:',mape(y_test_onehot, y_predict))

ValueError: ignored